### ISSUE TITLE
Incompatibilty with BriefingRoom, need to update mist.lua

### ISSUE THREAD

**Issue by AlucardleVash** [Pax1601/DCSOlympus#820] opened 2024-02-04 20:11 UTC
Hello,

Is it possible to update to last mist.lua version ?

Currently, we're having problems with the version of mist that is incompatible between Olympus and BriefingRoom. 
The connection with the backend works fine, but no aircraft or models are visible. (Spawn is possible, but the device disappears immediately).
After testing using the same version as BriefingRoom, there are no more problems on the horizon. 
They are currently running 4.5.122

Best regards

**Comment by AlucardleVash** [comment] 2024-02-04 20:12
Here the current error
```
2024-02-04 13:01:44.680 ERROR   SCRIPTING (Main): Mission script error: [string "F:/Saved Games/DCS/Mods/Services/Olympus/bin/../Scripts/mist.lua"]:3908: attempt to index field '?' (a nil value)
stack traceback:
    [C]: ?
    [string "F:/Saved Games/DCS/Mods/Services/Olympus/bin/../Scripts/mist.lua"]:3908: in function 'getPayload'
    [string "F:/Saved Games/DCS/Mods/Services/Olympus/bin/../Scripts/OlympusCommand.lua"]:1093: in function <[string "F:/Saved Games/DCS/Mods/Services/Olympus/bin/../Scripts/OlympusCommand.lua"]:968>
    ```

**Comment by Pax1601** [comment] 2024-02-07 17:17
Thank you very much for the additional info. I'm closing this as duplicate of #745 but we will definitely fix it in the next release

**Closed by Pax1601** 2024-02-07 17:17 UTC
