### ISSUE TITLE
IADS Zone will spawn units dangling off of buildings in cities

### ISSUE THREAD

**Issue by WirtsLegs** [Pax1601/DCSOlympus#554] opened 2023-11-19 21:44 UTC
Suggest testing with a small search for statics at intended spawn location, if location blocked use [getClosestPointOnRoads()](https://wiki.hoggitworld.com/view/DCS_func_getClosestPointOnRoads) and spawn there.

for larger sites it may be more complicated

**Comment by WirtsLegs** [comment] 2023-11-19 21:49
update: just found issue 550, related/same thing

**Comment by Pax1601** [comment] 2023-11-20 08:50
Duplicate of #550

**Closed** 2023-11-22 08:24 UTC
Labels: bug, backend
