### ISSUE TITLE
Add in ability to select an area and delete all units within

### ISSUE THREAD

**Issue by bobprofisker** [Pax1601/DCSOlympus#28] opened 2023-02-10 13:12 UTC
Select and delete, say for undoing big mistakes, or if running a campaign on the same thing over and over can delete areas where in prior missions things will be safe.

Needs to not delete things in one go, they need to trickle to prevent lag, needs a are you sure or obvious mode that you are in it.

**Comment by PeekabooSteam** [comment] 2023-02-22 15:21
Closing as a duplicate of #15 .

**Comment by Pax1601** [comment] 2023-05-11 07:14
Implemented by other issues

**Closed by Pax1601** 2023-05-11 07:14 UTC
Labels: enhancement
