### ISSUE TITLE
double click on unit behaviour

### ISSUE THREAD

**Issue by doz8ball** [Pax1601/DCSOlympus#387] opened 2023-09-15 12:54 UTC
Sometimes double clicking appears not to select a unit, a successive click will select all units of that type when the intent was to select the one.

It seems left clicking on a unit while having a unit selected deselects all while counting as a click on the unit

**Comment by PeekabooSteam** [comment] 2023-09-22 09:15
Closing as duplicate of #388

**Closed by PeekabooSteam** 2023-09-22 09:15 UTC
Labels: bug, frontend
