### ISSUE TITLE
AI Aircraft Instructed to land do not in land at airfield as instructed

### ISSUE THREAD

**Issue by Shredmetal** [Pax1601/DCSOlympus#637] opened 2023-12-02 18:25 UTC
Spawn a group of 4 jets, instructed them to land at airfield, they flew to airfield, overflew it, and house icon in Olympus changes to red triangle with exclamation mark in it, and they just turned around to return to where they spawned from.

Tested on:

Marianas
Sinai
Syria

With same results.

When unit ran low on fuel, they would go to any nearby airbase to land.

**Comment by Pax1601** [comment] 2023-12-03 19:58
Duplicate of #381

**Closed by Pax1601** 2023-12-03 19:58 UTC
