### ISSUE TITLE
Spawn in zone doesn't respect the selected coalition

### ISSUE THREAD

**Issue by bobprofisker** [Pax1601/DCSOlympus#547] opened 2023-11-19 17:43 UTC
When using the spawn AAA, etc, in a pre mapped zone it spawns both coalitions units which is a bit crap would be nice to only spawn things tagged as red or blue coalition

**Comment by Pax1601** [comment] 2023-11-22 08:24
Duplicate of #555

**Closed by Pax1601** 2023-11-22 08:24 UTC
Labels: bug, frontend, UI
