### ISSUE TITLE
Utility aircraft and ground unit collaboration

### ISSUE THREAD

**Issue by doz8ball** [Pax1601/DCSOlympus#135] opened 2023-03-24 09:45 UTC
A system were by it appears that ground units such as infantry, and light enough vehicles, embark and disembark from utility aircraft like helicopters and cargo aircraft.

Should show laden status of the aircraft

Bonus: affect weight and performance of aircraft.

**Comment by Pax1601** [comment] 2023-11-22 08:28
Duplicate of #285

**Closed** 2023-11-22 08:28 UTC
Labels: enhancement
