### ISSUE TITLE
Spawn heading and speed

### ISSUE THREAD

**Issue by YukikazeMua** [Pax1601/DCSOlympus#717] opened 2023-12-14 00:24 UTC
Could you please include the option to specify the direction and initial velocity when creating units? Additionally, is it possible to use in-game maps instead of the current ones? It seems that using satellite maps may result in positional discrepancies.

**Comment by WoodyXP** [comment] 2023-12-14 01:13
Hi there,

Unfortunately, we won't be able to include the feature for spawning a unit with a chosen heading and speed in the initial release. However, we plan to add this feature at a later date.

Regarding the map, it's challenging to modify the in-game map for external use, and some discrepancies might still occur. Currently, only the Georgia map has noticeable discrepancies. Other maps, like PG or Syria, are functioning well as they are.

We are also considering the introduction of DCS maps as an option in the future.

**Comment by WirtsLegs** [comment] 2023-12-20 16:14
related to (sorta dupe of) https://github.com/Pax1601/DCSOlympus/issues/557

**Closed** 2024-12-07 18:24 UTC
Labels: enhancement, frontend
