### ISSUE TITLE
Deleting a ground unit that has a player in it deletes the unit from game but not the icon.

### ISSUE THREAD

**Issue by bobprofisker** [Pax1601/DCSOlympus#480] opened 2023-10-29 12:51 UTC
Deleting a ground unit that has a player in it via combined arms deletes the unit from game but never the icon in Olympus until you delete it again.

Olympus client tested.

**Comment by Pax1601** [comment] 2023-11-03 08:04
Probably duplicate of https://github.com/Pax1601/DCSOlympus/issues/483

**Closed by Pax1601** 2023-11-03 08:04 UTC
Labels: bug
